### ISSUE TITLE
[BUG] Невозможно построить относительный путь до каталога

### ISSUE THREAD

**Issue by PRO100MIXA** [1c-syntax/bsl-language-server#1276]
**Версия**
> 0.15.2

**Описание ошибки диагностики**
> В случае если каталог исполняемого файла и каталога с файлами для анализа различаются происходит ошибка анализа

**Пример кода**

> "C:\Program Files (x86)\bsl-language-server\bsl-language-server.exe" -a -s R:\Temp\2\v8_69E6_52.tmp\ -o R:\Temp\2\v8_69E6_52.tmp\ -r json

**Скриншоты**
> http://joxi.ru/a2X4X10uwe3GY2?d=1

**Дополнительная информация**
```
Analyzing files... 100% [===========================================================================================================] 1/1 (0:00:00 / 0:00:00)
java.lang.IllegalArgumentException: 'other' has different root
        at java.base/sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at com.github._1c_syntax.bsl.languageserver.cli.AnalyzeCommand.getFileInfoFromFile(AnalyzeCommand.java:204)
        at com.github._1c_syntax.bsl.languageserver.cli.AnalyzeCommand.lambda$call$1(AnalyzeCommand.java:180)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
        at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.github._1c_syntax.bsl.languageserver.cli.AnalyzeCommand.call(AnalyzeCommand.java:182)
        at com.github._1c_syntax.bsl.languageserver.cli.AnalyzeCommand.call(AnalyzeCommand.java:80)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at com.github._1c_syntax.bsl.languageserver.BSLLSPLauncher.main(BSLLSPLauncher.java:96)
```

**Comment by PRO100MIXA** [comment]
Оказалось что если разместить и сам сервер на этом диске происходит такая же ошибка.
Для создания диска использовал SoftPerfect RAM Disk

**Comment by asosnoviy** [comment]
А зачем тут -o ?

**Comment by nixel2007** [comment]
попробуйте передать параметр workdir. в случае его отсутствия, относительный путь для данных анализа строится от CWD. а судя по вашей строке запуска, запускается он не из корня проекта, и не пойми от куда.

**Comment by PRO100MIXA** [comment]
> 
> 
> попробуйте передать параметр workdir. в случае его отсутствия, относительный путь для данных анализа строится от CWD. а судя по вашей строке запуска, запускается он не из корня проекта, и не пойми от куда.

Да, указание рабочего каталога помогло, спасибо

**Comment by zeegin** [comment]
А чего закрыли-то? Надо сделать внятную ошибку чтоб не гадать.
У меня сейчас тоже самое взорвалось.
