### ISSUE TITLE
[IllegalArgumentException] AllFunctionPathMustHaveReturnDiagnostic

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#1774]
**Версия**
0.19.0-rc1
**Описание ошибки диагностики**
```
no such vertex in graph: com.github._1c_syntax.bsl.languageserver.cfg.BasicBlockVertex@177f7a1a
java.lang.IllegalArgumentException: no such vertex in graph: com.github._1c_syntax.bsl.languageserver.cfg.BasicBlockVertex@177f7a1a
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
	at org.jgrapht.graph.AbstractBaseGraph.incomingEdgesOf(AbstractBaseGraph.java:464)
	at com.github._1c_syntax.bsl.languageserver.cfg.CfgBuildingParseTreeVisitor.hasNoSignificantEdges(CfgBuildingParseTreeVisitor.java:165)
	at com.github._1c_syntax.bsl.languageserver.cfg.CfgBuildingParseTreeVisitor.visitPreproc_endif(CfgBuildingParseTreeVisitor.java:480)
	at com.github._1c_syntax.bsl.languageserver.cfg.CfgBuildingParseTreeVisitor.visitPreproc_endif(CfgBuildingParseTreeVisitor.java:34)
	at com.github._1c_syntax.bsl.parser.BSLParser$Preproc_endifContext.accept(BSLParser.java:840)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitPreprocessor(BSLParserBaseVisitor.java:179)
	at com.github._1c_syntax.bsl.parser.BSLParser$PreprocessorContext.accept(BSLParser.java:1441)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitStatement(BSLParserBaseVisitor.java:659)
	at com.github._1c_syntax.bsl.parser.BSLParser$StatementContext.accept(BSLParser.java:5403)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitCodeBlock(BSLParserBaseVisitor.java:595)
	at com.github._1c_syntax.bsl.languageserver.cfg.CfgBuildingParseTreeVisitor.visitCodeBlock(CfgBuildingParseTreeVisitor.java:194)
	at com.github._1c_syntax.bsl.languageserver.cfg.CfgBuildingParseTreeVisitor.visitCodeBlock(CfgBuildingParseTreeVisitor.java:34)
	at com.github._1c_syntax.bsl.parser.BSLParser$CodeBlockContext.accept(BSLParser.java:4770)
	at com.github._1c_syntax.bsl.languageserver.cfg.CfgBuildingParseTreeVisitor.buildGraph(CfgBuildingParseTreeVisitor.java:68)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AllFunctionPathMustHaveReturnDiagnostic.checkAllPathsHaveReturns(AllFunctionPathMustHaveReturnDiagnostic.java:102)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AllFunctionPathMustHaveReturnDiagnostic.visitFunction(AllFunctionPathMustHaveReturnDiagnostic.java:94)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AllFunctionPathMustHaveReturnDiagnostic.visitFunction(AllFunctionPathMustHaveReturnDiagnostic.java:52)
	at com.github._1c_syntax.bsl.parser.BSLParser$FunctionContext.accept(BSLParser.java:2845)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitSub(BSLParserBaseVisitor.java:331)
	at com.github._1c_syntax.bsl.parser.BSLParser$SubContext.accept(BSLParser.java:2729)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitSubs(BSLParserBaseVisitor.java:323)
	at com.github._1c_syntax.bsl.parser.BSLParser$SubsContext.accept(BSLParser.java:2662)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitFile(BSLParserBaseVisitor.java:43)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractVisitorDiagnostic.getDiagnostics_aroundBody0(AbstractVisitorDiagnostic.java:46)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractVisitorDiagnostic$AjcClosure1.run(AbstractVisitorDiagnostic.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.github._1c_syntax.bsl.languageserver.aop.MeasuresAspect.measureBSLDiagnostic(MeasuresAspect.java:58)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractVisitorDiagnostic.getDiagnostics(AbstractVisitorDiagnostic.java:44)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractDiagnosticTest.getDiagnostics(AbstractDiagnosticTest.java:83)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractDiagnosticTest.getDiagnostics(AbstractDiagnosticTest.java:88)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.AllFunctionPathMustHaveReturnDiagnosticTest.testDefaultBehavior(AllFunctionPathMustHaveReturnDiagnosticTest.java:41)
```
**Пример кода**
> Пример кода (в блоке code или прикрепленный файл), на котором ошибка воспроизводится
```
Функция Тест()
    Список = Новый СписокЗначений;

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда
    Если Условие Тогда
    Иначе
    КонецЕсли;
#КонецЕсли

Возврат Список;
КонецФункции
```
**Скриншоты**
> Скриншоты с подтверждением

**Дополнительная информация**
> Любая дополнительная информация, которая поможет в расследовании проблемы

**Comment by nixel2007** [comment]
@EvilBeaver твой фикс можно вливать или ты ещё работаешь?

**Comment by EvilBeaver** [comment]
да, для данной диагностики фикса достаточно
