### ISSUE TITLE
Ошибка подсчета номеров строк при использовании getContentList и одиночных CR

### ISSUE THREAD

**Issue by nagdevops2** [1c-syntax/bsl-language-server#1789]
Здравствуйте.

Ошибки:

УТ подобных ошибок много

ERROR: Can't compute TextRange for given Range
java.lang.IllegalArgumentException: 57 is not a valid line offset for pointer. File Trade/CommonModules/УправлениеКонтактнойИнформацией/Ext/Module.bsl has 55 character(s) at line 2365
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getTextRange(IssuesLoader.java:231)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getNewIssueLocation(IssuesLoader.java:215)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.createIssue(IssuesLoader.java:99)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$processFile$5(BSLCoreSensor.java:197)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:197)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:172)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/82443902/131615897-1a2d2dfa-d791-48e9-a39b-23d968967107.png)

ЕРП единичные случаи:

ERROR: Can't compute TextRange for given Range
java.lang.IllegalArgumentException: 83 is not a valid line offset for pointer. File ERP/CommonModules/НАГ_УниверсальныеМеханизмы/Ext/Module.bsl has 12 character(s) at line 1612
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getTextRange(IssuesLoader.java:231)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.getNewIssueLocation(IssuesLoader.java:215)
	at com.github._1c_syntax.bsl.sonar.IssuesLoader.createIssue(IssuesLoader.java:99)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$processFile$5(BSLCoreSensor.java:197)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:197)
	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$3(BSLCoreSensor.java:172)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/82443902/131615795-7f93901a-ae35-4f6e-8f50-7173c7d509a9.png)

**Comment by nixel2007** [comment]
@asosnoviy @otymko стрельнул getContentList() на одиночных CR

https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java#L318

Как думаете, можем ли мы безболезненно изменить регулярку на `\r?\n|\r` ?

**Comment by nixel2007** [comment]
@nagdevops2 добрый день. Должно быть исправлено в свежей сборке https://t.me/bsl_language_server/76187

**Comment by nagdevops2** [comment]
Здравствуйте.

Спасибо. Проверим.

ср, 8 сент. 2021 г. в 13:01, Nikita Gryzlov ***@***.***>:
