### ISSUE TITLE
[BUG] NestedFunctionInParameters NPE

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#2722]
## Диагностика

NestedFunctionInParameters

## Версия

ночная сборка от 01.04.2022 на базе v0.20.0-rc.2 

## Пример кода

```
ERROR: Diagnostic computation error.
File: file:///.../src/cf/CommonModules/���������HTTP/Ext/Module.bsl
Diagnostic: Either [
  left = NestedFunctionInParameters
  right = null
]
java.lang.NullPointerException: null
	at com.github._1c_syntax.bsl.languageserver.diagnostics.NestedFunctionInParametersDiagnostic.findNestedCall(NestedFunctionInParametersDiagnostic.java:96)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.NestedFunctionInParametersDiagnostic.checkMethodCall(NestedFunctionInParametersDiagnostic.java:[109](https://git-1c.infostart.ru/Infostart/infostart-edu-bot/-/jobs/33636#L109))
	at com.github._1c_syntax.bsl.languageserver.diagnostics.NestedFunctionInParametersDiagnostic.visitGlobalMethodCall(NestedFunctionInParametersDiagnostic.java:62)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.NestedFunctionInParametersDiagnostic.visitGlobalMethodCall(NestedFunctionInParametersDiagnostic.java:34)
	at com.github._1c_syntax.bsl.parser.BSLParser$GlobalMethodCallContext.accept(BSLParser.java:6550)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitComplexIdentifier(BSLParserBaseVisitor.java:779)
	at com.github._1c_syntax.bsl.parser.BSLParser$ComplexIdentifierContext.accept(BSLParser.java:6653)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
```

**Comment by nixel2007** [comment]
Пример кода?
