### ISSUE TITLE
[BUG] ExtraCommas NPE

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#2723]
## Диагностика

ExtraCommas

## Версия

ночная сборка от 01.04.2022 на базе v0.20.0-rc.2

## Пример кода

```
ERROR: Diagnostic computation error.
File: file:///.../src/cf/CommonModules/���������HTTP/Ext/Module.bsl
Diagnostic: Either [
  left = ExtraCommas
  right = null
]
java.lang.NullPointerException: null
	at com.github._1c_syntax.bsl.languageserver.diagnostics.ExtraCommasDiagnostic.visitCallParamList(ExtraCommasDiagnostic.java:46)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.ExtraCommasDiagnostic.visitCallParamList(ExtraCommasDiagnostic.java:31)
	at com.github._1c_syntax.bsl.parser.BSLParser$CallParamListContext.accept(BSLParser.java:5699)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitDoCall(BSLParserBaseVisitor.java:835)
	at com.github._1c_syntax.bsl.parser.BSLParser$DoCallContext.accept(BSLParser.java:7124)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitGlobalMethodCall(BSLParserBaseVisitor.java:763)
	at com.github._1c_syntax.bsl.parser.BSLParser$GlobalMethodCallContext.accept(BSLParser.java:6550)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
	at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitComplexIdentifier(BSLParserBaseVisitor.java:779)
```

**Comment by nixel2007** [comment]
Пример кода?
