### ISSUE TITLE
[BUG] Diagnostic computation error

### ISSUE THREAD

**Issue by Snitkovski** [1c-syntax/bsl-language-server#2883]
Environment:

SonarQube Community, version 9.4.0.54424
1C (BSL) Community Plugin 1.10.0
Community Branch Plugin 1.11.0

Error description:

96% [======================================> ] 2161/2251 (0:01:14 / 0:00:03) ERROR: Diagnostic computation error.

File: file:///github/workspace/c3_edt/src/Configuration/ManagedApplicationModule.bsl

Diagnostic: Either [
left = SetPermissionsForNewObjects
right = null
]

java.lang.NullPointerException: null
at com.github._1c_syntax.bsl.languageserver.diagnostics.SetPermissionsForNewObjectsDiagnostic.lambda$check$0(SetPermissionsForNewObjectsDiagnostic.java:71)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
at com.github._1c_syntax.bsl.languageserver.diagnostics.SetPermissionsForNewObjectsDiagnostic.check(SetPermissionsForNewObjectsDiagnostic.java:75)
at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractDiagnostic.getDiagnostics_aroundBody0(AbstractDiagnostic.java:44)
at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractDiagnostic$AjcClosure1.run(AbstractDiagnostic.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
at com.github._1c_syntax.bsl.languageserver.aop.MeasuresAspect.measureBSLDiagnostic(MeasuresAspect.java:59)
at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractDiagnostic.getDiagnostics(AbstractDiagnostic.java:42)
at com.github._1c_syntax.bsl.languageserver.context.computer.DiagnosticComputer.lambda$compute$0(DiagnosticComputer.java:48)
at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:411)
at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at com.github._1c_syntax.bsl.languageserver.context.computer.DiagnosticComputer.compute_aroundBody0(DiagnosticComputer.java:62)
at com.github._1c_syntax.bsl.languageserver.context.computer.DiagnosticComputer$AjcClosure1.run(DiagnosticComputer.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
at com.github._1c_syntax.bsl.languageserver.aop.MeasuresAspect.measureComputers(MeasuresAspect.java:96)
at com.github._1c_syntax.bsl.languageserver.context.computer.DiagnosticComputer.compute(DiagnosticComputer.java:43)
at com.github._1c_syntax.bsl.languageserver.context.DocumentContext.computeDiagnostics(DocumentContext.java:408)
at com.github._1c_syntax.utils.Lazy.maybeCompute(Lazy.java:76)
at com.github._1c_syntax.utils.Lazy.getOrCompute(Lazy.java:53)
at com.github._1c_syntax.utils.Lazy.getOrCompute(Lazy.java:61)
at com.github._1c_syntax.bsl.languageserver.context.DocumentContext.getDiagnostics(DocumentContext.java:250)
at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.processFile(BSLCoreSensor.java:198)
at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$4(BSLCoreSensor.java:174)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

97% [=======================================>] 2195/2251 (0:01:15 / 0:00:01)

**Comment by nixel2007** [comment]
@Snitkovski тэкс, а каталог с ролями можно?
