### ISSUE TITLE
[BUG] - Символ # в наименовании папок и файлов

### ISSUE THREAD

**Issue by Ordo-ordinans** [1c-syntax/bsl-language-server#2996]
### **Версия** 
`v0.21.0-ra.5`
 
**Пример наименования:** 
`D:\## 1C ##\Внешние обработки\`

**Сервер:**
```
 1. Инициализируется.
 2. Контекст наполняется. Бывает прерывается, бывает идет постоянное наполнение.
```
### **Описание ошибки**
Когда в наименовании папки встречается символ "#"
**Не работает:**
```
1. Переход к определению.
2. Всплывающие подсказки при наведении.

```
**Всплывающие уведомления:**
```
1. Request textDocument/hover failed.
2. Request textDocument/definition failed.
3. Request textDocument/foldingRange failed.
4. Request textDocument/codeLens failed.
```

При этом они могут быть, а могут и нет. 

**Скриншоты**

![изображение](https://user-images.githubusercontent.com/105869781/219962588-a8219c95-1dc3-4f4b-a152-9cf1f83412e8.png)

![изображение](https://user-images.githubusercontent.com/105869781/219962631-e99a01c8-ae07-4a6d-b0ae-9734a0915812.png)

![изображение](https://user-images.githubusercontent.com/105869781/219963178-8a8d649b-a94f-4883-803a-dd093a3aa855.png)

https://user-images.githubusercontent.com/105869781/219961702-ed896e72-abd3-4a42-8b6f-124e6495307c.mp4

**Дополнительная информация**

**Request textDocument/hover failed.**
```
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI.create(Unknown Source)
	at com.github._1c_syntax.utils.Absolute.uri(Absolute.java:60)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:149)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:136)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.hover(BSLTextDocumentService.java:124)
	... 17 more
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	... 22 more

```
** Request textDocument/definition failed.**
  ```
Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI.create(Unknown Source)
	at com.github._1c_syntax.utils.Absolute.uri(Absolute.java:60)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:149)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:136)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.definition(BSLTextDocumentService.java:137)
	... 17 more
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	... 22 more

```
**Request textDocument/foldingRange failed.**
```
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI.create(Unknown Source)
	at com.github._1c_syntax.utils.Absolute.uri(Absolute.java:60)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:149)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:136)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.foldingRange(BSLTextDocumentService.java:228)
	... 17 more
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	... 22 more
```
**Request textDocument/codeLens failed.**
```
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI.create(Unknown Source)
	at com.github._1c_syntax.utils.Absolute.uri(Absolute.java:60)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:149)
	at com.github._1c_syntax.bsl.languageserver.context.ServerContext.getDocument(ServerContext.java:136)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.codeLens(BSLTextDocumentService.java:186)
	... 17 more
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 14: file:///d%3A/##%201C%20##/Внешние%20обработки/Сведения%20о%20внешней%20обработке%20—%20копия.bsl
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	... 22 more
```

**Comment by nixel2007** [comment]
Спасибо за такой подробный репорт.

**Comment by Ordo-ordinans** [comment]
Не за что, по мне так как-то даже поверхностно. 
Вопрос: с этим символом в наименованиях сильно заморочно разобраться?
Просто не хотелось бы структуру папок на машинах менять.

**Comment by nixel2007** [comment]
Нужно будет пошаманить в библиотеке #1c-syntax/utils. Сложно пока сказать.
