### ISSUE TITLE
Ошибка при работе фонового задания в сонар

### ISSUE THREAD

**Issue by ksv87** [1c-syntax/bsl-language-server#312]
![image](https://user-images.githubusercontent.com/15774585/62847519-603f4980-bcdf-11e9-83ac-163305494768.png)
![image](https://user-images.githubusercontent.com/15774585/62847530-6a614800-bcdf-11e9-9f06-d626d75ecd59.png)

**Comment by ksv87** [comment]
es.log 2019.08.12 00:00:15 WARN  es[][o.e.c.r.a.DiskThresholdMonitor] flood stage disk watermark [95%] exceeded on [VYW_EDgfTjeHsEl5gQi5SA][sonarqube][D:\sonarqube-7.9.1\data\es6\nodes\0] free: 7.8gb[3.4%], all indices on this node will be marked read-only

**Comment by ksv87** [comment]
ce.log 2019.08.12 08:48:29 INFO  ce[AWyEVzFWYyMoa1FvxCtz][o.s.c.t.s.ComputationStepExecutor] Purge db | status=SUCCESS | time=3526ms
2019.08.12 08:48:29 ERROR ce[][o.s.s.es.BulkIndexer] index [projectmeasures], type [auth], id [AWyEVzDcYyMoa1FvxCtt], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.08.12 08:48:29 INFO  ce[AWyEVzFWYyMoa1FvxCtz][o.s.c.t.s.ComputationStepExecutor] Index analysis | status=FAILED | time=224ms
2019.08.12 08:48:34 ERROR ce[AWyEVzFWYyMoa1FvxCtz][o.s.c.t.CeWorkerImpl] Failed to execute task AWyEVzFWYyMoa1FvxCtz
java.lang.IllegalStateException: Unrecoverable indexation failures: 1 errors among 1 requests
	at org.sonar.server.es.IndexingListener$1.onFinish(IndexingListener.java:39)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:122)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.doIndex(ProjectMeasuresIndexer.java:158)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.indexOnAnalysis(ProjectMeasuresIndexer.java:82)
	at org.sonar.ce.task.projectanalysis.step.IndexAnalysisStep.execute(IndexAnalysisStep.java:45)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019.08.12 08:48:36 INFO  ce[AWyEVzFWYyMoa1FvxCtz][o.s.c.t.CeWorkerImpl] Executed task | project=Tax | type=REPORT | id=AWyEVzFWYyMoa1FvxCtz | status=FAILED | time=499043ms

**Comment by nixel2007** [comment]
Судя по логам, либо место на диске закончилось, либо не хватает памяти для search процесса.

Какие настройки стоят для sonar.search.javaOpts в конфиге сонара?

**Comment by ksv87** [comment]
sonar.search.javaOpts=-Xms5g -Xmx6g -XX:+HeapDumpOnOutOfMemoryError

на диске 15Гб свободно из 226, этого мало?

**Comment by nixel2007** [comment]
Это чуть больше 6 процентов. Вероятно при построении индексов количество занятого места становится больше, чем 95%, и срабатывает защитный механизм от переполнения диска, встроенный в es. Есть возможность перенести установку на другой диск?

**Comment by ksv87** [comment]
почистил диск, 40Гб свободно, запустил еще раз, как результат будет напишу

**Comment by ksv87** [comment]
Ошибка осталась
2019.08.12 11:12:05 INFO  ce[AWyEpfxpYyMoa1FvxCuA][o.s.c.t.s.ComputationStepExecutor] Purge db | status=SUCCESS | time=16161ms
2019.08.12 11:12:05 ERROR ce[][o.s.s.es.BulkIndexer] index [projectmeasures], type [auth], id [AWyEpfxDYyMoa1FvxCt6], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.08.12 11:12:05 INFO  ce[AWyEpfxpYyMoa1FvxCuA][o.s.c.t.s.ComputationStepExecutor] Index analysis | status=FAILED | time=10ms
2019.08.12 11:12:10 ERROR ce[AWyEpfxpYyMoa1FvxCuA][o.s.c.t.CeWorkerImpl] Failed to execute task AWyEpfxpYyMoa1FvxCuA
java.lang.IllegalStateException: Unrecoverable indexation failures: 1 errors among 1 requests
	at org.sonar.server.es.IndexingListener$1.onFinish(IndexingListener.java:39)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:122)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.doIndex(ProjectMeasuresIndexer.java:158)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.indexOnAnalysis(ProjectMeasuresIndexer.java:82)
	at org.sonar.ce.task.projectanalysis.step.IndexAnalysisStep.execute(IndexAnalysisStep.java:45)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019.08.12 11:12:27 INFO  ce[AWyEpfxpYyMoa1FvxCuA][o.s.c.t.CeWorkerImpl] Executed task | project=Tax | type=REPORT | id=AWyEpfxpYyMoa1FvxCuA | status=FAILED | time=3966549ms

**Comment by ksv87** [comment]
2019.08.12 11:48:18 ERROR web[][o.s.s.es.BulkIndexer] index [components], type [auth], id [AWyEpqu_Gd_KuTOj4X8Y], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]

много вот атких ошибок в логах

**Comment by nixel2007** [comment]
остановите сервер, удалите каталог `%SONARQUBE_HOME%/data/es6` и попробуйте еще раз.
