### ISSUE TITLE
IOOBE при процедуре и имени процедуры на разных строках

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#323]
![codeAction](https://user-images.githubusercontent.com/1132840/63162772-19798880-c02c-11e9-9727-560f6a7f0196.gif)

```
��� 16, 2019 1:43:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IndexOutOfBoundsException: start 1, end 140, s.length() 109
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: start 1, end 140, s.length() 109
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: start 1, end 140, s.length() 109
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.context.DocumentContext.getText(DocumentContext.java:145)
	at org.github._1c_syntax.bsl.languageserver.diagnostics.SpaceAtStartCommentDiagnostic.lambda$getQuickFixes$2(SpaceAtStartCommentDiagnostic.java:119)
	at java.util.Collections$SingletonList.forEach(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.diagnostics.SpaceAtStartCommentDiagnostic.getQuickFixes(SpaceAtStartCommentDiagnostic.java:116)
	at org.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.getCodeActionsByDiagnostic(QuickFixCodeActionSupplier.java:73)
	at org.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.lambda$getCodeActions$0(QuickFixCodeActionSupplier.java:56)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.getCodeActions(QuickFixCodeActionSupplier.java:55)
	at org.github._1c_syntax.bsl.languageserver.providers.CodeActionProvider.getCodeActions(CodeActionProvider.java:93)
	at org.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.lambda$codeAction$1(BSLTextDocumentService.java:156)
	... 6 more

[Error - 13:43:07] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: start 1, end 140, s.length() 109
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: start 1, end 140, s.length() 109
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.context.DocumentContext.getText(DocumentContext.java:145)
	at org.github._1c_syntax.bsl.languageserver.diagnostics.SpaceAtStartCommentDiagnostic.lambda$getQuickFixes$2(SpaceAtStartCommentDiagnostic.java:119)
	at java.util.Collections$SingletonList.forEach(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.diagnostics.SpaceAtStartCommentDiagnostic.getQuickFixes(SpaceAtStartCommentDiagnostic.java:116)
	at org.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.getCodeActionsByDiagnostic(QuickFixCodeActionSupplier.java:73)
	at org.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.lambda$getCodeActions$0(QuickFixCodeActionSupplier.java:56)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.getCodeActions(QuickFixCodeActionSupplier.java:55)
	at org.github._1c_syntax.bsl.languageserver.providers.CodeActionProvider.getCodeActions(CodeActionProvider.java:93)
	at org.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.lambda$codeAction$1(BSLTextDocumentService.java:156)
	... 6 more
```

**Comment by nixel2007** [comment]
С учетом того, что IOOBE на квикфиксе, добавленном в текущем релизе, надо включать исправление сейчас.
