### ISSUE TITLE
NPE в DocumentSymbolProvider

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#368]
При наборе процедуры внутри области

```
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.lambda$getSubVariables$6(DocumentSymbolProvider.java:121)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.getSubVariables(DocumentSymbolProvider.java:128)
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.addMethod(DocumentSymbolProvider.java:97)
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.lambda$addRegion$5(DocumentSymbolProvider.java:81)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.addRegion(DocumentSymbolProvider.java:81)
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.lambda$getDocumentSymbol$0(DocumentSymbolProvider.java:53)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.github._1c_syntax.bsl.languageserver.providers.DocumentSymbolProvider.getDocumentSymbol(DocumentSymbolProvider.java:53)
	at org.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.lambda$documentSymbol$0(BSLTextDocumentService.java:147)
	... 6 more
```

**Comment by ovcharenko-di** [comment]
@nixel2007 , готов помочь пофиксить, но не удалось воспроизвести по этому описанию

**Comment by nixel2007** [comment]
@ovcharenko-di 

https://github.com/1c-syntax/bsl-language-server/blob/8045b6e89d491cdaefd9c936bf977af8c75d2f0f/src/main/java/org/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProvider.java#L121

пытаюсь понять, где тут может быть NPE, вроде везде по грамматике должен быть узел...
https://github.com/1c-syntax/bsl-parser/blob/master/src/main/antlr/BSLParser.g4#L137-L139

Лови гифку с воспроизведением. Падает после Процедура...

![npe](https://user-images.githubusercontent.com/1132840/65506847-3af44c80-ded5-11e9-9844-072a4734d620.gif)


Воспроизводил на вот этом репе, в модуле формы
https://github.com/nixel2007/tc-epf-template

**Comment by nixel2007** [comment]
@ovcharenko-di блин, я же сам аннотацию навесил.
`@Nullable BSLParser.SubVarsContext subVariablesContext`

скорее входящий параметр просто null. и надо его проверять и выходить из метода
