### ISSUE TITLE
Не работает диагностика SelfInsertionDiagnostic из-за MissingSpace

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#399]
Хотя тесты проекта и проходят, но в VSC происходить при анализе файла diagnostics\SelfInsertionDiagnostic.bsl следующее:
![image](https://user-images.githubusercontent.com/11651847/66253832-1d0dce00-e798-11e9-8604-734c00586093.png)

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.computeDiagnostics(DiagnosticProvider.java:111)
	at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.computeAndPublishDiagnostics(DiagnosticProvider.java:94)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.validate(BSLTextDocumentService.java:282)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.didSave(BSLTextDocumentService.java:265)
	... 16 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 113, Size: 113
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.MissingSpaceDiagnostic.noSpaceRight(MissingSpaceDiagnostic.java:255)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.MissingSpaceDiagnostic.lambda$getDiagnostics$2(MissingSpaceDiagnostic.java:133)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.MissingSpaceDiagnostic.getDiagnostics(MissingSpaceDiagnostic.java:134)
	at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.lambda$computeDiagnostics$0(DiagnosticProvider.java:110)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.util.stream.AbstractTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by otymko** [comment]
Так работает:
![image](https://user-images.githubusercontent.com/11651847/66254707-59dfc200-e7a4-11e9-9260-6d82af01b6c2.png)
Так нет:
![image](https://user-images.githubusercontent.com/11651847/66254712-682dde00-e7a4-11e9-82b1-20642234b56c.png)
