### ISSUE TITLE
NPE ExtraCommas

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#414]
```
Caused by: java.lang.NullPointerException
        at com.github._1c_syntax.bsl.languageserver.diagnostics.ExtraCommasDiagnostic.visitCallParamList(ExtraCommasDiagnostic.java:41)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.ExtraCommasDiagnostic.visitCallParamList(ExtraCommasDiagnostic.java:30)
        at com.github._1c_syntax.bsl.parser.BSLParser$CallParamListContext.accept(BSLParser.java:5425)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitDoCall(BSLParserBaseVisitor.java:713)
        at com.github._1c_syntax.bsl.parser.BSLParser$DoCallContext.accept(BSLParser.java:6589)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitNewExpression(BSLParserBaseVisitor.java:643)
        at com.github._1c_syntax.bsl.parser.BSLParser$NewExpressionContext.accept(BSLParser.java:6023)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitComplexIdentifier(BSLParserBaseVisitor.java:678)
        at com.github._1c_syntax.bsl.parser.BSLParser$ComplexIdentifierContext.accept(BSLParser.java:6290)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
```

**Comment by nixel2007** [comment]
callParamList может быть пустым https://github.com/1c-syntax/bsl-parser/blob/master/src/main/antlr/BSLParser.g4#L226-L227

**Comment by qtLex** [comment]
Если еще никто не брался. Я сделаю.
