### ISSUE TITLE
NPE при конфигурировании CognitiveComplexity

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#461]
**Версия**
Develop

```    
"CognitiveComplexity": {
      "complexityThreshold": 30
    }
```

```
Caused by: java.lang.NullPointerException
	at com.github._1c_syntax.bsl.languageserver.diagnostics.CognitiveComplexityDiagnostic.configure(CognitiveComplexityDiagnostic.java:74)
	at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.configureDiagnostic(DiagnosticProvider.java:400)
```

**Comment by asosnoviy** [comment]
Из за того, что не указан второй параметр   "checkModuleBody" : true
