### ISSUE TITLE
[BUG] QuickFixSupplier дергает лишние диагностики

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#623]
**Версия**
Develop

**Описание ошибки диагностики**
```
java.util.concurrent.CompletionException: java.lang.ClassCastException: class com.github._1c_syntax.bsl.languageserver.diagnostics.MethodSizeDiagnostic cannot be cast to class com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider (com.github._1c_syntax.bsl.languageserver.diagnostics.MethodSizeDiagnostic and com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider are in unnamed module of loader 'app')
```

**Пример кода**

**Скриншоты**

**Дополнительная информация**

В VSC переходим из панели проблем к любой ошибке, для которой нет квикфикса.

**Comment by asosnoviy** [comment]
```
����. 13, 2019 4:13:35 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.ClassCastException: class com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic cannot be cast to class com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider (com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic and com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider are in unnamed module of loader 'app')
java.util.concurrent.CompletionException: java.lang.ClassCastException: class com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic cannot be cast to class com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider (com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic and com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider are in unnamed module of loader 'app')
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassCastException: class com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic cannot be cast to class com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider (com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic and com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider are in unnamed module of loader 'app')
	at com.github._1c_syntax.bsl.languageserver.codeactions.QuickFixSupplier.getQuickFixInstance(QuickFixSupplier.java:65)
	at com.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.getCodeActionsByDiagnostic(QuickFixCodeActionSupplier.java:66)
	at com.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.lambda$processDiagnosticStream$0(QuickFixCodeActionSupplier.java:49)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github._1c_syntax.bsl.languageserver.codeactions.AbstractQuickFixSupplier.getCodeActions(AbstractQuickFixSupplier.java:65)
	at com.github._1c_syntax.bsl.languageserver.providers.CodeActionProvider.getCodeActions(CodeActionProvider.java:98)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.lambda$codeAction$1(BSLTextDocumentService.java:164)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 more

[Error - 16:13:35] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassCastException: class com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic cannot be cast to class com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider (com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic and com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider are in unnamed module of loader 'app')
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassCastException: class com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic cannot be cast to class com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider (com.github._1c_syntax.bsl.languageserver.diagnostics.IfElseIfEndsWithElseDiagnostic and com.github._1c_syntax.bsl.languageserver.diagnostics.QuickFixProvider are in unnamed module of loader 'app')
	at com.github._1c_syntax.bsl.languageserver.codeactions.QuickFixSupplier.getQuickFixInstance(QuickFixSupplier.java:65)
	at com.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.getCodeActionsByDiagnostic(QuickFixCodeActionSupplier.java:66)
	at com.github._1c_syntax.bsl.languageserver.codeactions.QuickFixCodeActionSupplier.lambda$processDiagnosticStream$0(QuickFixCodeActionSupplier.java:49)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github._1c_syntax.bsl.languageserver.codeactions.AbstractQuickFixSupplier.getCodeActions(AbstractQuickFixSupplier.java:65)
	at com.github._1c_syntax.bsl.languageserver.providers.CodeActionProvider.getCodeActions(CodeActionProvider.java:98)
	at com.github._1c_syntax.bsl.languageserver.BSLTextDocumentService.lambda$codeAction$1(BSLTextDocumentService.java:164)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 more


```
