### ISSUE TITLE
NPE TimeoutsInExternalResources

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#678]
```
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
  at com.github._1c_syntax.bsl.languageserver.diagnostics.TimeoutsInExternalResourcesDiagnostic.isTimeoutModifer(TimeoutsInExternalResourcesDiagnostic.java:180)
  at com.github._1c_syntax.bsl.languageserver.diagnostics.TimeoutsInExternalResourcesDiagnostic.lambda$checkNextStatement$2(TimeoutsInExternalResourcesDiagnostic.java:170)
  at java.base/java.util.ArrayList.forEach(Unknown Source)
  at com.github._1c_syntax.bsl.languageserver.diagnostics.TimeoutsInExternalResourcesDiagnostic.checkNextStatement(TimeoutsInExternalResourcesDiagnostic.java:166)
  at com.github._1c_syntax.bsl.languageserver.diagnostics.TimeoutsInExternalResourcesDiagnostic.lambda$visitCodeBlock$1(TimeoutsInExternalResourcesDiagnostic.java:151)
  at java.base/java.util.ArrayList.forEach(Unknown Source)
  at com.github._1c_syntax.bsl.languageserver.diagnostics.TimeoutsInExternalResourcesDiagnostic.visitCodeBlock(TimeoutsInExternalResourcesDiagnostic.java:138)
  at com.github._1c_syntax.bsl.languageserver.diagnostics.TimeoutsInExternalResourcesDiagnostic.visitCodeBlock(TimeoutsInExternalResourcesDiagnostic.java:42)
```

**Comment by theshadowco** [comment]
а есть исходник, на котором ломается?

**Comment by otymko** [comment]
Пока нету.

**Comment by theshadowco** [comment]
```          BSLParser.AccessPropertyContext accessProperty = (BSLParser.AccessPropertyContext) allRuleNodes.get(0);
          return patternTimeout.matcher(accessProperty.getText()).find();```

**Comment by theshadowco** [comment]
180 - это возврат, т.е. accessProperty - null либо getText - null
