### ISSUE TITLE
[BUG] ArrayIndexOutOfBoundsException при попытке проверить, что один квик фикс закрывает две диагностики

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#764]
**Версия**
> Версия BSLLS либо плагина, который использует BSLLS
0.12.3

**Описание ошибки диагностики**
Предположим, что один квик фикс может закрыть сразу две диагностики, так как у них пересекается область. Например диагностика пустых областей. Если в пустой внешней области есть пустая внутренняя область, то один квик фикс должен закрыть сразу две диагностики.

Проверка осуществляется новым апи.
**Пример кода**
```
    List<Diagnostic> diagnostics = getDiagnostics();
    final Diagnostic externalRegionDiagnostic = diagnostics.get(1);
    final Diagnostic internalRegionDiagnostic = diagnostics.get(2);

    List<CodeAction> quickFixes = getQuickFixes(externalRegionDiagnostic);

    assertThat(quickFixes).hasSize(1);

    final CodeAction quickFix = quickFixes.get(0);

    assertThat(quickFix).of(diagnosticInstance).in(documentContext)
      .fixes(internalRegionDiagnostic);

    assertThat(quickFix).of(diagnosticInstance).in(documentContext)
      .fixes(externalRegionDiagnostic);

    assertThat(quickFix).in(documentContext)
      .hasChanges(1)
      .hasNewText("");
```

**Дополнительная информация**
Вывод консоли:
```
Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.github._1c_syntax.bsl.languageserver.context.DocumentContext.getText(DocumentContext.java:179)
	at com.github._1c_syntax.bsl.languageserver.util.assertions.CodeActionAssert.lambda$fixes$0(CodeActionAssert.java:82)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github._1c_syntax.bsl.languageserver.util.assertions.CodeActionAssert.fixes(CodeActionAssert.java:69)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.EmptyRegionDiagnosticTest.testQuickFix(EmptyRegionDiagnosticTest.java:71)
```

**Comment by qtLex** [comment]
Если никто не против я это возьму
