### ISSUE TITLE
[BUG] Падает сборка gradle на этапе :updateDiagnosticDocs если в папке libs есть несколько билдов.

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#767]
**Версия**
0.12.3

**Описание ошибки диагностики**
Если в папке билдов находится несколько билдов следующего формата:
```
bsl-language-server-OSUsersDiagnostic-6b85343.jar		24.12.2019 10:33
bsl-language-server-OSUsersDiagnostic-829e149-DIRTY.jar		24.12.2019 14:24
bsl-language-server-OSUsersDiagnostic-5849743-DIRTY.jar 	24.12.2019 18:49
bsl-language-server-OSUsersDiagnostic-f491113-DIRTY.jar		24.12.2019 14:16
```

То при выполнения команды `gradlew precommit` сборка падает на этапе updateDiagnosticDocs со следующей ошибкой:
```

Caused by: java.util.MissingResourceException: Can't find bundle for base name com.github._1c_syntax.bsl.languageserver.diagnostics.MultilingualStringHasAllDeclaredLanguagesDiagnostic, locale ru
        at com.github._1c_syntax.bsl.languageserver.diagnostics.metadata.DiagnosticInfo.getResourceString(DiagnosticInfo.java:113)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.metadata.DiagnosticParameterInfo.lambda$createDiagnosticParameters$0(DiagnosticParameterInfo.java:86)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.metadata.DiagnosticParameterInfo.createDiagnosticParameters(DiagnosticParameterInfo.java:87)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.metadata.DiagnosticInfo.<init>(DiagnosticInfo.java:64)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.DiagnosticSupplier.getDiagnosticInstance(DiagnosticSupplier.java:88)
        ... 195 more
```

**Comment by theshadowco** [comment]
Убил кучу времени - увы, плавающая ошибка периодически всплывает. 
Нормально отрабатывает после clean.

Есть предложение отказаться от gradle скриптов и дальше варианты:
- отдельная либа (java, kotlin, groove, etc), которая сделает тоже, что и скрипты
- функционал внутри bslls, в режиме dev сборки добавляющий ф-ии скриптов (можно и  консольном режимом)

Ну а дальше, в градле скриптом дернуть эту фунцию
