### ISSUE TITLE
[BUG]NPE NonStandardRegionDiagnostic

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#803]
## Диагностика
NonStandardRegionDiagnostic

## Версия
 13 alfa

## Дополнительная информация

```
Caused by: java.lang.NullPointerException
	at com.github._1c_syntax.bsl.languageserver.diagnostics.NonStandardRegionDiagnostic.lambda$visitFile$1(NonStandardRegionDiagnostic.java:184)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.github._1c_syntax.bsl.languageserver.diagnostics.NonStandardRegionDiagnostic.visitFile(NonStandardRegionDiagnostic.java:181)
```

**Comment by theshadowco** [comment]
есть пример файлега?

**Comment by theshadowco** [comment]
падает на строке `Ranges.create(region.getStartNode().getStart(), region.getStartNode().getStop())` 
Что здесь может быть null?

**Comment by nixel2007** [comment]
region? :) отлаживаться надо
