### ISSUE TITLE
[BUG] NestedFunctionInParameters NPE

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#991]
## Диагностика

NestedFunctionInParameters

## Версия
develop

## Описание ошибки диагностики

NullPointerException в модуле [Module.txt](https://github.com/1c-syntax/bsl-language-server/files/4314884/Module.txt)

## Дополнительная информация

`Analyzing files...  73% [===============>     ] 5191/7056 (0:04:17 / 0:01:32) [ForkJoinPool.commonPool-worker-7] ERROR com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider - Diagnostic computation error.
File: file:///E:/projects/OneCAutoservice/autoservice/src/Documents/МассоваяРассылка/Forms/ФормаДокумента/Module.bsl
Diagnostic: NestedFunctionInParameters
Analyzing files...  74% [===============>     ] 5227/7056 (0:04:18 / 0:01:30) java.lang.NullPointerException
        at com.github._1c_syntax.bsl.languageserver.diagnostics.NestedFunctionInParametersDiagnostic.visitNewExpression(NestedFunctionInParametersDiagnostic.java:69)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.NestedFunctionInParametersDiagnostic.visitNewExpression(NestedFunctionInParametersDiagnostic.java:34)
        at com.github._1c_syntax.bsl.parser.BSLParser$NewExpressionContext.accept(BSLParser.java:6225)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitComplexIdentifier(BSLParserBaseVisitor.java:771)
        at com.github._1c_syntax.bsl.parser.BSLParser$ComplexIdentifierContext.accept(BSLParser.java:6498)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitMember(BSLParserBaseVisitor.java:723)
        at com.github._1c_syntax.bsl.parser.BSLParser$MemberContext.accept(BSLParser.java:6111)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitExpression(BSLParserBaseVisitor.java:683)
        at com.github._1c_syntax.bsl.parser.BSLParser$ExpressionContext.accept(BSLParser.java:5722)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitAssignment(BSLParserBaseVisitor.java:659)
        at com.github._1c_syntax.bsl.parser.BSLParser$AssignmentContext.accept(BSLParser.java:5499)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitStatement(BSLParserBaseVisitor.java:651)
        at com.github._1c_syntax.bsl.parser.BSLParser$StatementContext.accept(BSLParser.java:5312)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitCodeBlock(BSLParserBaseVisitor.java:587)
        at com.github._1c_syntax.bsl.parser.BSLParser$CodeBlockContext.accept(BSLParser.java:4698)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitSubCodeBlock(BSLParserBaseVisitor.java:371)
        at com.github._1c_syntax.bsl.parser.BSLParser$SubCodeBlockContext.accept(BSLParser.java:3168)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitProcedure(BSLParserBaseVisitor.java:339)
        at com.github._1c_syntax.bsl.parser.BSLParser$ProcedureContext.accept(BSLParser.java:2801)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitSub(BSLParserBaseVisitor.java:331)
        at com.github._1c_syntax.bsl.parser.BSLParser$SubContext.accept(BSLParser.java:2738)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitSubs(BSLParserBaseVisitor.java:323)
        at com.github._1c_syntax.bsl.parser.BSLParser$SubsContext.accept(BSLParser.java:2671)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:48)
        at com.github._1c_syntax.bsl.parser.BSLParserBaseVisitor.visitFile(BSLParserBaseVisitor.java:43)
        at com.github._1c_syntax.bsl.languageserver.diagnostics.AbstractVisitorDiagnostic.getDiagnostics(AbstractVisitorDiagnostic.java:46)
        at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.lambda$computeDiagnostics$0(DiagnosticProvider.java:77)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
        at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:411)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.github._1c_syntax.bsl.languageserver.providers.DiagnosticProvider.computeDiagnostics(DiagnosticProvider.java:91)
        at com.github._1c_syntax.bsl.languageserver.cli.AnalyzeCommand.getFileInfoFromFile(AnalyzeCommand.java:107)
        at com.github._1c_syntax.bsl.languageserver.cli.AnalyzeCommand.lambda$execute$0(AnalyzeCommand.java:83)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

**Comment by theshadowco** [comment]
падает на таком коде

```
	КлючЗаписи = Новый(
	Тип("РегистрСведенийКлючЗаписи.ОчередьРассылок"),
	ОбщегоНазначенияКлиентСервер.ЗначениеВМассиве(Отбор));
```
